### ISSUE TITLE
Use Bulk Data from Scryfall

### ISSUE THREAD

**Issue by matAlmeida** [matAlmeida/pauper-api#1]
## current listing cards function:
- Get the nth page from `scryfall/cards` and return only the cards that is `pauper legal`. Occasionally a page can has 0 pauper legal cards.

## improving the functionality of listing the cards:
- Fetch the `scryfall/bulk-data` hourly or daily and use that offline data instead of their api. We can go thought every card after fetch and leave only the `pauper legal` ones. So the Pauper Api would became faster.

------

## Tasks

- [x] create a `cronjob` routine daily
- [x] function to fetch `bulk_data`
- [x] function to sanitize fetched data with only pauper legal cards
- [x] set the `cronjob` to run the routine on server start
- [ ] create a way to do `fuzzy matching` on the card names [https://fusejs.io/](https://fusejs.io/)
- [ ] update all lists `endpoint` to use the fetched data.
